# src/main/resources/plugin.yml
name: sNightVision
version: '${project.version}'
main: org.sinnaz3153.nightvision.Nightvision
api-version: '26.1.1'
author: "sinnaz3153"
description: "§bA simple plugin to toggle nightvision effect"
website: 'https://github.com/sinnaz3153/sNightvision'

commands:
  nightvision:
    description: "Toggle nightvision effect"
    usage: "/<command> [player]"
    aliases: [nv, snv, snightvision]
  nightvisionadmin:
    description: "Admin commands for nightvision"
    usage: "/<command> reload"
    permission: "nightvision.admin"
    aliases: [nvadmin, snvadmin, snightvisionadmin]

permissions:
  snightvision.use:
    description: Allows using the nightvision command
    default: true
  snightvision.use.other:
    description: Allows toggling nightvision for other players
    default: op
  snightvision.admin:
    description: Allows using admin commands
    default: op